[platformio]
default_envs = esp32s3_devkitc1_n16r8

[env:esp32s3_devkitc1_n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 16MB
board_build.flash_mode = dio
board_build.psram = enabled
board_build.arduino.memory_type = qspi_opi
upload_speed = 921600
monitor_speed = 115200
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

[env:esp32s3_n16r8_full]
platform = espressif32
board = esp32s3-devkitc-1
framework = arduino

board_build.flash_size = 16MB
board_build.flash_mode = qio
board_build.flash_freq = 80m

board_build.psram_type = qspi
board_build.psram_size = 8MB

build_flags =
    -DWLED_USE_PSRAM
    -DWLED_MM_FULL
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

board_build.partitions = tools/WLED_16MB.csv

