[platformio]
default_envs = esp32s3_wroom_1_n16nb

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.flash_freq = 80m
board_build.filesystem = littlefs
board_build.partitions = tools/WLED_ESP32_16MB.csv

build_flags =
  -D WLED_RELEASE_NAME=\"WLED-MM\"
  -D WLED_USE_PSRAM
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_RUNNING_CORE=1
  -D ARDUINO_EVENT_RUNNING_CORE=1
  -D CONFIG_FREERTOS_HZ=1000

lib_deps =
  makuna/NeoPixelBus@^2.7.9

extra_scripts =
  pio-scripts/build_ui.py
  pio-scripts/set_version.py
  pio-scripts/set_repo.py
  pio-scripts/output_bins.py

[env:esp32s3_wroom_1_n16nb]
extends = env
board = esp32-s3-devkitc-1
board_upload.flash_size = 16MB
board_build.psram = opi
build_flags =
  ${env.build_flags}
  -D WLEDMM_S3_N16R8
