name: Build WLED-MM S3 N16R8

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout WLED-MM
        uses: actions/checkout@v4

      - name: Checkout WLED-MM source
        uses: actions/checkout@v4
        with:
            repository: MoonModules/WLED-MM
            ref: mdev
            path: wledmm
            clean: false
            fetch-depth: 0
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply custom config
        run: |
          cp platformio.ini wledmm/platformio.ini
          cp sdkconfig.defaults wledmm/sdkconfig.defaults

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: |
          cd wledmm
          pio run -e esp32s3_devkitc1_n16r8

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-esp32s3_devkitc1_n16r8
          path: wledmm/.pio/build/esp32s3_devkitc1_n16r8/firmware.bin
